# Generated by Django 2.1.5 on 2019-01-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_md', models.TextField(blank=True, null=True)),
                ('article_html', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('article_md_en', models.TextField(blank=True, null=True)),
                ('article_html_en', models.TextField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'article',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=255)),
                ('tab_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'tab',
                'db_table': 'tabs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('tag_en', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'tag',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Tag')),
            ],
            options={
                'verbose_name_plural': 'tagmap',
                'db_table': 'tagmaps',
            },
        ),
        migrations.CreateModel(
            name='Toppage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_md', models.TextField(blank=True, null=True)),
                ('article_html', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('article_md_en', models.TextField(blank=True, null=True)),
                ('article_html_en', models.TextField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'toppage',
                'db_table': 'toppage',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Series'),
        ),
    ]
