# Generated by Django 2.1.5 on 2019-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190202_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
