# Generated by Django 2.2.2 on 2019-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessbleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_flag', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kana', models.CharField(blank=True, max_length=255, null=True)),
                ('name_initial', models.CharField(blank=True, max_length=4, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, '不明'), (1, '男性'), (2, '女性'), (3, '適用不能')], null=True)),
                ('academic_background', models.CharField(blank=True, max_length=255, null=True)),
                ('nearlest_station', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('good_at_task', models.TextField(blank=True, null=True)),
                ('pr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Porject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('charge', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('total_size', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('db', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('framework', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('search', models.BooleanField(default=False)),
                ('requirements', models.BooleanField(default=False)),
                ('basic_design', models.BooleanField(default=False)),
                ('detail_design', models.BooleanField(default=False)),
                ('dev_and_unit', models.BooleanField(default=False)),
                ('join_test', models.BooleanField(default=False)),
                ('test', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('dev_env', models.BooleanField(default=False)),
            ],
        ),
    ]
